/**
 * Cafe Eleganza - Complete Seed Data
 * All prices editable in admin and flagged "// CLIENT TO CONFIRM".
 * Handcrafted with high-quality descriptions, Urdu translations, allergens, and dietary tags.
 */

import { MenuItem, Category, Review, PromoCode, FAQItem, TableItem } from './types';

export const seedCategories: Category[] = [
  { id: 'cat-seasonal', name: 'Seasonal & New', nameUr: 'موسمی و نیا', slug: 'seasonal', order: 1, icon: 'Sparkles', active: true },
  { id: 'cat-coffee', name: 'Artisan Coffee', nameUr: 'دست کار کافی', slug: 'coffee', order: 2, icon: 'Coffee', active: true },
  { id: 'cat-signature', name: 'Signature Flavors', nameUr: 'خاص ذائقے', slug: 'signature-flavors', order: 3, icon: 'Flame', active: true },
  { id: 'cat-frappe', name: 'Frappuccinos', nameUr: 'فریپوچینو', slug: 'frappuccinos', order: 4, icon: 'IceCream', active: true },
  { id: 'cat-limka', name: 'Limka Coolers', nameUr: 'لمکا کولرز', slug: 'limka-coolers', order: 5, icon: 'GlassWater', active: true },
  { id: 'cat-mocktails', name: 'Virgin Mocktails', nameUr: 'ورجن موکٹیلز', slug: 'mocktails', order: 6, icon: 'Wine', active: true },
  { id: 'cat-tea', name: 'Heritage Teas', nameUr: 'روایتی چائے', slug: 'heritage-teas', order: 7, icon: 'CupSoda', active: true },
  { id: 'cat-east', name: 'East Corner', nameUr: 'ایسٹ کارنر (ایشین)', slug: 'east-corner', order: 8, icon: 'UtensilsCrossed', active: true },
  { id: 'cat-pizza', name: 'Wood-Fired Pizza', nameUr: 'ووڈ فائرڈ پیزا', slug: 'pizza', order: 9, icon: 'Pizza', active: true },
  { id: 'cat-favorites', name: 'Cafe Favorites & Steaks', nameUr: 'کیفے فضل اور اسٹیکس', slug: 'favorites', order: 10, icon: 'Beef', active: true },
];

export const seedMenuItems: MenuItem[] = [
  // --- SEASONAL ---
  {
    id: 'item-ube-latte',
    name: 'Ube Latte',
    nameUr: 'اوبے لاٹے',
    slug: 'ube-latte',
    description: 'Soft, nutty, and a little unexpected. Filipino purple yam layered over silky steamed milk and bold espresso.',
    descriptionUr: 'ملائم، گری دار میوے دار اور خوشگوار انوکھا ذائقہ۔ اوبے پرپل یام اور خاص ایسپریسو کا شاندار امتزاج۔',
    categoryId: 'cat-seasonal',
    price: 820, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80',
    tags: ['Seasonal', 'The Ube Plan', 'Signature'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 280,
    isVeg: true,
    isSpicy: false,
    isNew: true,
    isPopular: true,
    isFeatured: true,
    available: true,
    stockCount: 45,
    lowStockThreshold: 10,
    variants: [
      { name: 'Iced Ube Latte', nameUr: 'آئسڈ اوبے لاٹے', priceDelta: 0 },
      { name: 'Warm Velvet Ube', nameUr: 'گرم اوبے لاٹے', priceDelta: 30 },
    ],
    addOns: [
      { name: 'Extra Ube Cream Cloud', nameUr: 'اضافی اوبے کریم', price: 120 },
      { name: 'Oat Milk Sub', nameUr: 'اوٹ ملک', price: 180 },
    ],
    sortOrder: 1,
  },

  // --- ARTISAN COFFEE ---
  {
    id: 'item-americano',
    name: 'Americano',
    nameUr: 'امریکنو',
    slug: 'americano',
    description: 'Double shot of high-altitude Arabica pulled over hot water for a crisp, rich crema and floral aroma.',
    descriptionUr: 'گرم پانی پر خاص عربیکا ایسپریسو کا ڈبل شاٹ، خوشبودار اور بھرپور ذائقہ۔',
    categoryId: 'cat-coffee',
    price: 700, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    tags: ['Classic', 'Black Coffee'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 10,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [{ name: 'Hot', priceDelta: 0 }, { name: 'Iced', priceDelta: 40 }],
    addOns: [{ name: 'Extra Shot', price: 150 }],
    sortOrder: 2,
  },
  {
    id: 'item-espresso',
    name: 'Espresso',
    nameUr: 'ایسپریسو',
    slug: 'espresso',
    description: 'Pure, concentrated single-origin extraction with golden crema and notes of dark cocoa and hazelnut.',
    descriptionUr: 'خالص مرکوز ایسپریسو شاٹ، جس میں ڈارک کوکو اور ہیزل نٹ کے دلکش نوٹس شامل ہیں۔',
    categoryId: 'cat-coffee',
    price: 580, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80',
    tags: ['Single Origin', 'Intense'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 5,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [{ name: 'Single Shot', priceDelta: 0 }, { name: 'Doppio (Double)', priceDelta: 160 }],
    addOns: [],
    sortOrder: 3,
  },
  {
    id: 'item-latte',
    name: 'Eleganza Latte',
    nameUr: 'الیگانزا لاٹے',
    slug: 'eleganza-latte',
    description: 'Silky microfoam poured delicately over rich dark roast espresso with swan latte art.',
    descriptionUr: 'ریشمی مائیکروفوم دودھ اور ڈارک روسٹ ایسپریسو کا شاہکار لاٹے آرٹ۔',
    categoryId: 'cat-coffee',
    price: 780, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=800&q=80',
    tags: ['Smooth', 'Latte Art'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 190,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [{ name: 'Standard Milk', priceDelta: 0 }, { name: 'Almond Milk', priceDelta: 150 }],
    addOns: [{ name: 'Vanilla Syrup', price: 120 }, { name: 'Caramel Drizzle', price: 120 }],
    sortOrder: 4,
  },
  {
    id: 'item-cappuccino',
    name: 'Cappuccino',
    nameUr: 'کیپوچینو',
    slug: 'cappuccino',
    description: 'Equal thirds of robust espresso, steamed milk, and airy velvety foam dusted with Belgian cocoa.',
    descriptionUr: 'ایسپریسو، بھاپ پر تیار دودھ اور ہلکی جھاگ بیلجیئم کوکو کے ساتھ۔',
    categoryId: 'cat-coffee',
    price: 750, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    tags: ['Classic', 'Velvety'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 150,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Shot', price: 150 }],
    sortOrder: 5,
  },
  {
    id: 'item-cafe-mocha',
    name: 'Cafe Mocha',
    nameUr: 'کیفے موکا',
    slug: 'cafe-mocha',
    description: 'Decadent dark Dutch chocolate ganache melted with fresh espresso and textured whole milk.',
    descriptionUr: 'ڈچ چاکلیٹ گاناش، تازہ ایسپریسو اور کریم دودھ کا دلکش اشتراک۔',
    categoryId: 'cat-coffee',
    price: 850, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80',
    tags: ['Chocolate', 'Indulgent'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 290,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [{ name: 'Dark Chocolate', priceDelta: 0 }, { name: 'White Chocolate', priceDelta: 50 }],
    addOns: [{ name: 'Whipped Cream', price: 100 }],
    sortOrder: 6,
  },
  {
    id: 'item-macchiato',
    name: 'Macchiato',
    nameUr: 'ماکیاٹو',
    slug: 'macchiato',
    description: 'Fresh espresso "marked" with a dollop of thick microfoam for a punchy, silky finish.',
    descriptionUr: 'تازہ ایسپریسو جس پر ریشمی مائیکروفوم کی ہلکی سی جھاگ سجائی گئی ہے۔',
    categoryId: 'cat-coffee',
    price: 700, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1557006021-b85faa2bc5e2?auto=format&fit=crop&w=800&q=80',
    tags: ['Punchy'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 30,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 7,
  },
  {
    id: 'item-spanish-latte',
    name: 'Spanish Latte',
    nameUr: 'ہسپانوی لاٹے',
    slug: 'spanish-latte',
    description: 'Rich condensed milk base topped with freshly pulled espresso shots and steamed whole milk.',
    descriptionUr: 'شیریں کنڈینسڈ دودھ کی تہوں کے ساتھ تازہ ایسپریسو شاٹس۔ بے حد مقبول!',
    categoryId: 'cat-coffee',
    price: 650, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    tags: ['Sweet', 'Bestseller'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 260,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [{ name: 'Iced', priceDelta: 0 }, { name: 'Hot', priceDelta: 0 }],
    addOns: [{ name: 'Cinnamon Dust', price: 50 }, { name: 'Extra Flavor', price: 160 }],
    sortOrder: 8,
  },
  {
    id: 'item-cold-coffee',
    name: 'Cold Coffee Classic',
    nameUr: 'کلاسک کولڈ کافی',
    slug: 'cold-coffee-classic',
    description: 'Creamy slow-blended coffee served over crystal ice blocks with a swirl of caramel cream.',
    descriptionUr: 'برف اور ریشمی کریم کے ساتھ بلینڈ کی گئی ٹھنڈی دلکش کافی۔',
    categoryId: 'cat-coffee',
    price: 720, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80',
    tags: ['Chilled', 'Refreshing'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 210,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [{ name: 'Vanilla Ice Cream Scoop', price: 160 }],
    sortOrder: 9,
  },

  // --- SIGNATURE FLAVORS ---
  {
    id: 'item-galao',
    name: 'Galao',
    nameUr: 'گالاؤ (پرتگالی کافی)',
    slug: 'galao',
    description: 'Portuguese breakfast staple: one-quarter espresso and three-quarters foamed milk served in tall glass.',
    descriptionUr: 'پرتگالی روایتی لمبا گلاس کافی جس میں دودھ کی نرمی اور کافی کا توازن ہے۔',
    categoryId: 'cat-signature',
    price: 860, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80',
    tags: ['Portuguese', 'Signature'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 180,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Flavor', price: 160 }],
    sortOrder: 10,
  },
  {
    id: 'item-mazagran',
    name: 'Mazagran',
    nameUr: 'مازاگرین (کافی لیمونیڈ)',
    slug: 'mazagran',
    description: 'Original cold coffee creation: chilled espresso shaken over ice with fresh Meyer lemon juice and cane sugar syrup.',
    descriptionUr: 'ٹھنڈی ایسپریسو، تازہ لیموں کا رس اور گنے کے شربت کا شاندار ریفریشنگ امتزاج۔',
    categoryId: 'cat-signature',
    price: 740, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
    tags: ['Citrus', 'Cold Brew Fusion'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 90,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [{ name: 'Mint Boost', price: 80 }],
    sortOrder: 11,
  },
  {
    id: 'item-lungo',
    name: 'Lungo',
    nameUr: 'لونگو',
    slug: 'lungo',
    description: 'Long-pulled espresso taking twice the water through the grounds for subtle smoky and roasted notes.',
    descriptionUr: 'دیرپا کشید کردہ ایسپریسو جس میں بھنی ہوئی کافی کے لطیف ذائقے ابھرتے ہیں۔',
    categoryId: 'cat-signature',
    price: 700, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    tags: ['Artisan Pull'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 5,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 12,
  },
  {
    id: 'item-long-black',
    name: 'Long Black',
    nameUr: 'لانگ بلیک',
    slug: 'long-black',
    description: 'Hot water topped with a full double shot of extraction, keeping the rich crema pristine and aromatic.',
    descriptionUr: 'گرم پانی پر تیرتا ہوا تازہ ڈبل شاٹ ایسپریسو جس پر بھرپور جھاگ قائم رہتی ہے۔',
    categoryId: 'cat-signature',
    price: 690, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    tags: ['Aromatic'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 5,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 13,
  },
  {
    id: 'item-affogato',
    name: 'Eleganza Affogato',
    nameUr: 'الیگانزا افوگاٹو',
    slug: 'eleganza-affogato',
    description: 'Artisanal Tahitian vanilla bean ice cream drowned in a hot shot of freshly pulled dark espresso.',
    descriptionUr: 'وانیلا بین آئس کریم کا بڑا اسکوپ جس پر گرم گرم کڑک ایسپریسو ڈالی گئی ہے۔ لاجواب میٹھا!',
    categoryId: 'cat-signature',
    price: 800, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80',
    tags: ['Dessert Coffee', 'New'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 220,
    isVeg: true,
    isSpicy: false,
    isNew: true,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [],
    addOns: [{ name: 'Toasted Almond Flakes', price: 90 }, { name: 'Caramel Swirl', price: 90 }],
    sortOrder: 14,
  },

  // --- FRAPPUCCINO ---
  {
    id: 'item-mocha-glacier',
    name: 'Mocha Glacier Frappe',
    nameUr: 'موکا گلیشیئر فریپے',
    slug: 'mocha-glacier-frappe',
    description: 'Blended espresso, Belgian dark chocolate chips, dairy milk, topped with peaks of mountain whipped cream.',
    descriptionUr: 'بلینڈڈ ایسپریسو، بیلجیئم ڈارک چاکلیٹ چپس اور جھاگ دار وپڈ کریم۔',
    categoryId: 'cat-frappe',
    price: 850, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    tags: ['Blended', 'Indulgent'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 380,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Choc Chips', price: 80 }, { name: 'Caramel Drizzle', price: 80 }],
    sortOrder: 15,
  },
  {
    id: 'item-caramel-crunch-frappe',
    name: 'Caramel Crunch Frappe',
    nameUr: 'کیریمل کرنچ فریپے',
    slug: 'caramel-crunch-frappe',
    description: 'Sweet golden caramel sauce blended with roast coffee and buttery toffee crunch bits.',
    descriptionUr: 'سنہری کیریمل شربت، روسٹڈ کافی اور ٹافی کرنچ کے ذرات کے ساتھ بلینڈ کیا گیا۔',
    categoryId: 'cat-frappe',
    price: 890, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1530373239216-42518e6b4063?auto=format&fit=crop&w=800&q=80',
    tags: ['Caramel', 'Crunch'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 410,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 16,
  },
  {
    id: 'item-java-chip-frappe',
    name: 'Java Chip Frappe',
    nameUr: 'جاوا چِپ فریپے',
    slug: 'java-chip-frappe',
    description: 'Mocha drizzle and blended chocolate flakes with dark roast espresso and cracked ice.',
    descriptionUr: 'موکا سوس اور باریک چاکلیٹ فلیکس کے ساتھ بلینڈ کی گئی ٹھنڈی جاوا کافی۔',
    categoryId: 'cat-frappe',
    price: 820, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&w=800&q=80',
    tags: ['Chocolate Lovers'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 360,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 17,
  },

  // --- LIMKA COOLERS ---
  {
    id: 'item-limka-citrus-spark',
    name: 'Limka Citrus Spark',
    nameUr: 'لمکا سیٹرس اسپارک',
    slug: 'limka-citrus-spark',
    description: 'Signature fizzy handcrafted cooler with fresh pressed lime, black salt, and crisp sparkling tonic.',
    descriptionUr: 'دست ساز لیموں کا لمکا، کالا نمک اور کرسپ اسپارکلنگ واٹر۔ بے حد تازہ دم!',
    categoryId: 'cat-limka',
    price: 590, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    tags: ['Handcrafted', 'Cooler', 'Fizzy'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 85,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [],
    addOns: [{ name: 'Mint Boost', price: 60 }, { name: 'Crushed Ice Extra', price: 40 }],
    sortOrder: 18,
  },
  {
    id: 'item-limka-berry-burst',
    name: 'Limka Berry Brust',
    nameUr: 'لمکا بیری برسٹ',
    slug: 'limka-berry-burst',
    description: 'Wild strawberry and blackberry infusion with bubbling artisan soda and fresh mint leaves.',
    descriptionUr: 'اسٹرابیری اور بلیک بیری کا تروتازہ رس، تیز فز اور تازہ پودینے کے پتے۔',
    categoryId: 'cat-limka',
    price: 650, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80',
    tags: ['Berries', 'Fizzy'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 110,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Berries', price: 90 }],
    sortOrder: 19,
  },
  {
    id: 'item-limka-blue-freeze',
    name: 'Limka Blue Freeze',
    nameUr: 'لمکا بلیو فریز',
    slug: 'limka-blue-freeze',
    description: 'Electric blue curaçao syrup, citrus zest, and chilled effervescent soda served with lemon slices.',
    descriptionUr: 'الیکٹرک بلیو سیرپ، لیموں کا چھلکا اور تیز جھاگ دار ٹھنڈا سوڈا۔',
    categoryId: 'cat-limka',
    price: 650, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    tags: ['Cool Blue', 'Vibrant'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 105,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 20,
  },
  {
    id: 'item-limka-pepper-pop',
    name: 'Limka Pepper Pop',
    nameUr: 'لمکا پیپر پاپ',
    slug: 'limka-pepper-pop',
    description: 'Zesty lemonade shaken with crushed black peppercorns and pink Himalayan salt for an unforgettable kick.',
    descriptionUr: 'لیموں کا شربت جس میں کٹی ہوئی کالی مرچ اور گلابی ہمالیائی نمک کی ترنگ ہے۔',
    categoryId: 'cat-limka',
    price: 620, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=800&q=80',
    tags: ['Spiced Lemonade', 'Unique'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 1,
    calories: 75,
    isVeg: true,
    isSpicy: true,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 21,
  },
  {
    id: 'item-limka-lychee-lush',
    name: 'Limka Lychee Lush',
    nameUr: 'لمکا لیچی لَش',
    slug: 'limka-lychee-lush',
    description: 'Delicate floral lychee nectar shaken over ice and crowned with crackling soda bubbles.',
    descriptionUr: 'میٹھی لیچی کا شربت اور کرکرا سوڈا، گرم دوپہر کا بہترین ساتھی۔',
    categoryId: 'cat-limka',
    price: 650, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=800&q=80',
    tags: ['Floral', 'Exotic'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 95,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 22,
  },
  {
    id: 'item-limka-pine-chill',
    name: 'Limka Pine Chill',
    nameUr: 'لمکا پائن چِل',
    slug: 'limka-pine-chill',
    description: 'Tropical pineapple puree topped with sparkling soda and a pinch of chaat masala for local zing.',
    descriptionUr: 'تازہ انناس کا گودا، تیز سوڈا اور چٹپٹا ذائقہ۔',
    categoryId: 'cat-limka',
    price: 620, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80',
    tags: ['Tropical', 'Zesty'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 100,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 23,
  },

  // --- VIRGIN MOCKTAILS ---
  {
    id: 'item-mocktail-strawberry-sparkle',
    name: 'Strawberry Sparkle Mocktail',
    nameUr: 'اسٹرابیری اسپارکل موکٹیل',
    slug: 'strawberry-sparkle-mocktail',
    description: 'Crushed ripe strawberries, fresh lime wedges, sparkling water, and delicate elderflower notes.',
    descriptionUr: 'تازہ کچی اسٹرابیری، لیموں کا رس اور جھاگ دار فز۔',
    categoryId: 'cat-mocktails',
    price: 795, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=800&q=80',
    tags: ['Mocktail', 'Non-Alcoholic'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 120,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [
      { name: 'Light Fizz', priceDelta: 0 },
      { name: 'Classic Fizz', priceDelta: 0 },
      { name: 'Extra Bubbly', priceDelta: 0 },
    ],
    addOns: [
      { name: 'Crushed Ice Extra', price: 50 },
      { name: 'Mint Boost', price: 60 },
    ],
    sortOrder: 24,
  },
  {
    id: 'item-mocktail-blue-lagoon',
    name: 'Blue Lagoon Virgin Mocktail',
    nameUr: 'بلیو لاگون ورجن موکٹیل',
    slug: 'blue-lagoon-virgin-mocktail',
    description: 'Mediterranean blue curaçao syrup, hand-squeezed lemon, and carbonated sprite topped with maraschino cherry.',
    descriptionUr: 'بلیو سیرپ، تازہ لیموں اور چمکدار سوڈا جس پر چیری سجائی گئی ہے۔',
    categoryId: 'cat-mocktails',
    price: 795, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    tags: ['Cocktail Style', 'Refreshing'],
    allergens: [],
    dietary: ['Vegan', 'Halal', 'Gluten-free'],
    spiceLevel: 0,
    calories: 130,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [
      { name: 'Light Fizz', priceDelta: 0 },
      { name: 'Classic Fizz', priceDelta: 0 },
      { name: 'Extra Bubbly', priceDelta: 0 },
    ],
    addOns: [{ name: 'Mint Boost', price: 60 }],
    sortOrder: 25,
  },

  // --- HERITAGE TEAS ---
  {
    id: 'item-kashmiri-chai',
    name: 'Traditional Kashmiri Chai',
    nameUr: 'روایتی کشمیری چائے',
    slug: 'traditional-kashmiri-chai',
    description: 'Slow-brewed pink tea leaves simmered for hours with green cardamom, baking soda, and crushed pistachios & almonds.',
    descriptionUr: 'گھنٹوں پکی ہوئی گلابی کشمیری چائے، الائچی، پستے اور بادام کے ڈھیر کے ساتھ۔',
    categoryId: 'cat-tea',
    price: 550, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    tags: ['Heritage', 'Pink Tea', 'Winter Favorite'],
    allergens: ['Dairy', 'Nuts'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 160,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Crushed Pistachios', price: 80 }],
    sortOrder: 26,
  },
  {
    id: 'item-doodh-patti',
    name: 'Karak Doodh Patti',
    nameUr: 'کڑک دودھ پتی',
    slug: 'karak-doodh-patti',
    description: 'Simmered purely in rich buffalo milk with robust CTC tea leaves and bruised cardamom pods.',
    descriptionUr: 'خالص دودھ میں خوب پکی ہوئی کڑک چائے، الائچی کی دلکش مہک کے ساتھ۔',
    categoryId: 'cat-tea',
    price: 450, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=800&q=80',
    tags: ['Comfort', 'Desi Chai'],
    allergens: ['Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 140,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [{ name: 'Regular Sweet', priceDelta: 0 }, { name: 'Less Sugar', priceDelta: 0 }, { name: 'Sugar-Free', priceDelta: 0 }],
    addOns: [{ name: 'Ginger Slice', price: 30 }],
    sortOrder: 27,
  },

  // --- EAST CORNER ---
  {
    id: 'item-thai-oyster-chicken',
    name: 'Thai Oyster Chicken',
    nameUr: 'تھائی اوئسٹر چکن',
    slug: 'thai-oyster-chicken',
    description: 'Wok-tossed chicken strips glazed in savory premium oyster sauce, garlic, and fresh green bell peppers.',
    descriptionUr: 'واک میں تلی ہوئی چکن اسٹرپس، لذیز اوئسٹر سوس اور شملہ مرچ کے ساتھ۔',
    categoryId: 'cat-east',
    price: 1750, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    tags: ['Thai', 'Wok Tossed'],
    allergens: ['Soy'],
    dietary: ['Halal'],
    spiceLevel: 1,
    calories: 520,
    isVeg: false,
    isSpicy: true,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [{ name: 'With Egg Fried Rice', priceDelta: 200 }, { name: 'With Garlic Rice', priceDelta: 220 }],
    addOns: [],
    sortOrder: 28,
  },
  {
    id: 'item-chicken-chili-dry',
    name: 'Chicken Chili Dry',
    nameUr: 'چکن چلی ڈرائی',
    slug: 'chicken-chili-dry',
    description: 'Crispy marinated sliced chicken wok-fried with sliced fresh green chilies, ginger batons, and dark soy.',
    descriptionUr: 'کرسپی چکن، تیز ہری مرچیں، ادرک اور سویا سوس کا شاندار روایتی چلی ڈرائی۔',
    categoryId: 'cat-east',
    price: 1650, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80',
    tags: ['Spicy', 'Crispy'],
    allergens: ['Soy'],
    dietary: ['Halal'],
    spiceLevel: 2,
    calories: 490,
    isVeg: false,
    isSpicy: true,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [{ name: 'With Egg Fried Rice', priceDelta: 200 }],
    addOns: [],
    sortOrder: 29,
  },
  {
    id: 'item-beef-chili-dry',
    name: 'Beef Chili Dry',
    nameUr: 'بیف چلی ڈرائی',
    slug: 'beef-chili-dry',
    description: 'Tender prime beef strips flash-seared at high heat with crisp scallions and fiery green chilies.',
    descriptionUr: 'اعلیٰ کوالٹی بیف اسٹرپس، تیز آنچ پر تلی ہوئی ہری مرچوں اور پیاز کے ساتھ۔',
    categoryId: 'cat-east',
    price: 2450, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=800&q=80',
    tags: ['Prime Beef', 'Spicy'],
    allergens: ['Soy'],
    dietary: ['Halal'],
    spiceLevel: 2,
    calories: 580,
    isVeg: false,
    isSpicy: true,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [{ name: 'With Egg Fried Rice', priceDelta: 200 }],
    addOns: [],
    sortOrder: 30,
  },
  {
    id: 'item-mongolian-beef',
    name: 'Mongolian Beef',
    nameUr: 'منگولین بیف',
    slug: 'mongolian-beef',
    description: 'Crispy coated beef tossed in a sticky savory brown sugar garlic reduction with charred green onions.',
    descriptionUr: 'کرسپی بیف، لہسن اور گہری میٹھی سوس کے ساتھ لذیذ منگولین ذائقہ۔',
    categoryId: 'cat-east',
    price: 2495, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    tags: ['Savory Sweet', 'Popular'],
    allergens: ['Soy'],
    dietary: ['Halal'],
    spiceLevel: 1,
    calories: 610,
    isVeg: false,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [],
    sortOrder: 31,
  },

  // --- WOOD-FIRED PIZZA ---
  {
    id: 'item-pizza-pepperoni',
    name: 'Signature Pepperoni Pizza',
    nameUr: 'پیپرونی پیزا',
    slug: 'signature-pepperoni-pizza',
    description: 'Slow-fermented sourdough crust topped with San Marzano tomato sauce, fresh mozzarella, and spicy beef pepperoni cups.',
    descriptionUr: 'لکڑی کے تندور کا کھٹا خمیری کرسٹ، اطالوی ٹماٹر سوس، موزریلا چیز اور بیف پیپرونی۔',
    categoryId: 'cat-pizza',
    price: 1850, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80',
    tags: ['Wood-Fired', '9/10 Reviewed'],
    allergens: ['Gluten', 'Dairy'],
    dietary: ['Halal'],
    spiceLevel: 1,
    calories: 880,
    isVeg: false,
    isSpicy: true,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [{ name: '10 Inch Medium', priceDelta: 0 }, { name: '13 Inch Large', priceDelta: 450 }],
    addOns: [{ name: 'Extra Cheese', price: 200 }, { name: 'Jalapeno Slices', price: 100 }],
    sortOrder: 32,
  },
  {
    id: 'item-pizza-margherita',
    name: 'Classic Margherita Pizza',
    nameUr: 'کلاسک مارگریٹا پیزا',
    slug: 'classic-margherita-pizza',
    description: 'Wood-fired crust, sweet plum tomato sauce, melted fior di latte mozzarella, fresh sweet basil, and extra virgin olive oil.',
    descriptionUr: 'خالص موزریلا چیز، تازہ تلسی اور زیتون کے تیل سے سجا ہوا کلاسک مارگریٹا۔',
    categoryId: 'cat-pizza',
    price: 1750, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=800&q=80',
    tags: ['Vegetarian Classic', 'Neapolitan'],
    allergens: ['Gluten', 'Dairy'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 750,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: false,
    isFeatured: false,
    available: true,
    variants: [{ name: '10 Inch Medium', priceDelta: 0 }, { name: '13 Inch Large', priceDelta: 420 }],
    addOns: [],
    sortOrder: 33,
  },
  {
    id: 'item-pizza-spanish',
    name: 'Spanish Pizza',
    nameUr: 'ہسپانوی پیزا',
    slug: 'spanish-pizza',
    description: 'Smoked paprika chicken, roasted red peppers, caramelized onions, black olives, and melted aged white cheddar blend.',
    descriptionUr: 'سموکڈ پیپریکا چکن، بھنی ہوئی سرخ شملہ مرچ، پیاز اور چیز کا ہسپانوی امتزاج۔',
    categoryId: 'cat-pizza',
    price: 1890, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    tags: ['Chef Signature', 'Wood-Fired'],
    allergens: ['Gluten', 'Dairy'],
    dietary: ['Halal'],
    spiceLevel: 1,
    calories: 890,
    isVeg: false,
    isSpicy: false,
    isNew: true,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [{ name: '10 Inch Medium', priceDelta: 0 }, { name: '13 Inch Large', priceDelta: 450 }],
    addOns: [],
    sortOrder: 34,
  },

  // --- CAFE FAVORITES & STEAKS ---
  {
    id: 'item-chicken-bearnaise-steak',
    name: 'Chicken Bearnaise Steak',
    nameUr: 'چکن بیرنائز اسٹیک',
    slug: 'chicken-bearnaise-steak',
    description: 'Tender grilled chicken fillet smothered in velvety tarragon Bearnaise sauce, served with sauteed veggies and mash.',
    descriptionUr: 'گرلڈ چکن فلے پر تاراگون بیرنائز سوس، ساتھ تلی ہوئی سبزیاں اور نرم میشڈ پوٹیٹو۔',
    categoryId: 'cat-favorites',
    price: 2850, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    tags: ['Popular Steak', 'Customer Favorite'],
    allergens: ['Dairy', 'Eggs'],
    dietary: ['Halal'],
    spiceLevel: 0,
    calories: 780,
    isVeg: false,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [{ name: 'Mashed Potatoes', priceDelta: 0 }, { name: 'French Fries', priceDelta: 0 }],
    addOns: [{ name: 'Extra Bearnaise Sauce', price: 180 }],
    sortOrder: 35,
  },
  {
    id: 'item-mozzarella-sticks',
    name: 'Golden Mozzarella Sticks',
    nameUr: 'موزریلا چیز اسٹکس',
    slug: 'golden-mozzarella-sticks',
    description: 'Crispy herb-crusted mozzarella sticks served with our house slow-simmered marinara dip.',
    descriptionUr: 'کرسپی تلسی کرسٹ والی چیز اسٹکس، ساتھ تازہ مرینارا ڈپ۔ بچوں اور بڑوں کی پسند!',
    categoryId: 'cat-favorites',
    price: 1250, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1548340748-6d2b7d7da410?auto=format&fit=crop&w=800&q=80',
    tags: ['Appetizer', 'Cheesy'],
    allergens: ['Dairy', 'Gluten'],
    dietary: ['Vegetarian', 'Halal'],
    spiceLevel: 0,
    calories: 450,
    isVeg: true,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Dip', price: 90 }],
    sortOrder: 36,
  },
  {
    id: 'item-club-sandwich',
    name: 'Triple Decker Club Sandwich',
    nameUr: 'کلب سینڈوچ مع کرسپی چپس',
    slug: 'triple-decker-club-sandwich',
    description: 'Toasted brioche layers stacked with grilled shredded chicken, fried egg, cheese slice, lettuce, and homemade sauce.',
    descriptionUr: 'تین تہوں پر مشتمل بروش بریڈ، گرلڈ چکن، انڈا، چیز اور اسپیشل سوس، ساتھ کرسپی چپس۔',
    categoryId: 'cat-favorites',
    price: 1450, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    tags: ['Lunch', 'Hearty'],
    allergens: ['Gluten', 'Eggs', 'Dairy'],
    dietary: ['Halal'],
    spiceLevel: 0,
    calories: 680,
    isVeg: false,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: false,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Cheese Slice', price: 90 }],
    sortOrder: 37,
  },
  {
    id: 'item-creamy-pasta',
    name: 'Creamy Alfredo Pasta',
    nameUr: 'کریمی الفریڈو پاستا',
    slug: 'creamy-alfredo-pasta',
    description: 'Fettuccine ribbons tossed in a rich garlic parmesan cream sauce, finished with grilled herbed chicken and toasted bread.',
    descriptionUr: 'پاستا فٹوچینی، لہسن اور پرمیسن چیز کریم سوس، گرلڈ ہرب چکن اور بیکڈ بریڈ۔',
    categoryId: 'cat-favorites',
    price: 1850, // CLIENT TO CONFIRM
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=800&q=80',
    tags: ['Pasta', 'Comfort'],
    allergens: ['Dairy', 'Gluten'],
    dietary: ['Halal'],
    spiceLevel: 0,
    calories: 790,
    isVeg: false,
    isSpicy: false,
    isNew: false,
    isPopular: true,
    isFeatured: true,
    available: true,
    variants: [],
    addOns: [{ name: 'Extra Garlic Bread', price: 120 }],
    sortOrder: 38,
  },
];

export const seedReviews: Review[] = [
  {
    id: 'rev-1',
    userId: 'u-hassan',
    userName: 'Hassan Raza',
    rating: 5,
    comment: 'The ambiance, the food and especially their lattes are delicious. Faisalabad finally has a world-class solarium cafe experience.',
    createdAt: '2026-03-24',
    approved: true,
  },
  {
    id: 'rev-2',
    userId: 'u-amina',
    userName: 'Amina Khalid',
    rating: 5,
    comment: 'Pepperoni pizza 9/10, stuffed chicken 9/10! The crust had that perfect blistered wood-fire crunch. Will definitely return with family.',
    createdAt: '2026-03-28',
    approved: true,
  },
  {
    id: 'rev-3',
    userId: 'u-usman',
    userName: 'Usman Tariq',
    rating: 5,
    comment: 'Their Limka Citrus Spark and Spanish Latte are unmatched in the city. Incredible evening lighting under the glass roof.',
    createdAt: '2026-04-02',
    approved: true,
  },
  {
    id: 'rev-4',
    userId: 'u-zainab',
    userName: 'Zainab Fatima',
    rating: 5,
    comment: 'Ordered via table QR code. Zero wait time, order reached our table in 14 minutes piping hot. Great digital experience!',
    createdAt: '2026-04-04',
    approved: true,
  },
  {
    id: 'rev-5',
    userId: 'u-bilal',
    userName: 'Bilal Ahmed',
    rating: 5,
    comment: 'The Chicken Bearnaise Steak was cooked to absolute perfection. Creamy sauce without being heavy. 5 stars all the way.',
    createdAt: '2026-04-05',
    approved: true,
  },
  {
    id: 'rev-6',
    userId: 'u-maryam',
    userName: 'Maryam Noor',
    rating: 5,
    comment: 'Visual Diary photo series in the cafe gives it such a warm soul. Try the seasonal Ube Latte—creamy, nutty, and aesthetic!',
    createdAt: '2026-04-06',
    approved: true,
  },
];

export const seedPromos: PromoCode[] = [
  {
    id: 'promo-welcome10',
    code: 'WELCOME10',
    type: 'percent',
    value: 10,
    maxDiscount: 500,
    minOrder: 1500,
    startsAt: '2026-01-01',
    expiresAt: '2026-12-31',
    maxUses: 1000,
    timesUsed: 42,
    firstOrderOnly: true,
    orderTypes: ['delivery', 'pickup', 'dine_in'],
    active: true,
  },
  {
    id: 'promo-freedel',
    code: 'FREEDEL',
    type: 'freeDelivery',
    value: 250,
    minOrder: 3000,
    startsAt: '2026-01-01',
    expiresAt: '2026-12-31',
    maxUses: 500,
    timesUsed: 89,
    firstOrderOnly: false,
    orderTypes: ['delivery'],
    active: true,
  },
  {
    id: 'promo-eleganza5',
    code: 'ELEGANZA5',
    type: 'fixed',
    value: 200,
    minOrder: 2500,
    startsAt: '2026-01-01',
    expiresAt: '2026-12-31',
    maxUses: 200,
    timesUsed: 12,
    firstOrderOnly: false,
    orderTypes: ['delivery', 'pickup', 'dine_in'],
    active: true,
  },
];

export const seedTables: TableItem[] = Array.from({ length: 12 }, (_, i) => ({
  id: `tbl-${i + 1}`,
  number: String(i + 1),
  name: `Table ${i + 1} (${i < 4 ? 'Solarium Sunroom' : i < 8 ? 'Main Lounge' : 'Terrace Garden'})`,
  active: true,
  sessionCode: `ELG-T${i + 1}`,
}));

export const seedFAQs: FAQItem[] = [
  {
    questionEn: 'What are Cafe Eleganza’s operating hours?',
    questionUr: 'کیفے الیگانزا کے کھلنے کے اوقات کیا ہیں؟',
    answerEn: 'We are open daily from 11:00 AM until 12:00 AM (midnight), extending to 1:00 AM on Saturdays for evening gatherings.',
    answerUr: 'ہم روزانہ صبح 11:00 بجے سے رات 12:00 بجے تک کھلے رہتے ہیں، اور ہفتے کے روز رات 1:00 بجے تک سروس جاری رہتی ہے۔',
  },
  {
    questionEn: 'How does QR Table Ordering work?',
    questionUr: 'کیو آر ٹیبل آرڈرنگ کیسے کام کرتی ہے؟',
    answerEn: 'Simply scan the QR code located on your table with your phone camera. You can browse the bilingual menu, customize your order, and submit directly to our kitchen without waiting for staff.',
    answerUr: 'بس اپنے فون کے کیمرے سے ٹیبل پر موجود کیو آر کوڈ اسکین کریں۔ آپ مینو دیکھ سکتے ہیں، آرڈر کسٹمائز کر کے براہ راست کچن کو بھیج سکتے ہیں۔',
  },
  {
    questionEn: 'Do you offer home delivery in Faisalabad?',
    questionUr: 'کیا آپ فیصل آباد میں ہوم ڈلیوری فراہم کرتے ہیں؟',
    answerEn: 'Yes! We deliver across Raza Town, West Canal Road, Green Avenue, and greater Faisalabad. Free delivery applies on orders above Rs 3,000.',
    answerUr: 'جی ہاں! ہم رضا ٹاؤن، کینال روڈ، گرین ایونیو اور فیصل آباد کے دیگر علاقوں میں ہوم ڈلیوری فراہم کرتے ہیں۔ 3,000 روپے سے زائد کے آرڈر پر ڈلیوری مفت ہے۔',
  },
  {
    questionEn: 'Is your chicken and beef 100% Halal certified?',
    questionUr: 'کیا آپ کا تمام چکن اور بیف 100٪ حلال ہے؟',
    answerEn: 'Yes, absolutely. All meats, poultry, and ingredients used at Cafe Eleganza are strictly 100% Halal and freshly procured daily.',
    answerUr: 'جی بالکل۔ کیفے الیگانزا میں استعمال ہونے والا تمام گوشت اور اجزاء سختی سے 100٪ حلال اور روزانہ تازہ حاصل کیے جاتے ہیں۔',
  },
  {
    questionEn: 'Can I book a table or private event in advance?',
    questionUr: 'کیا میں ٹیبل یا نجی تقریب پہلے سے بک کر سکتا ہوں؟',
    answerEn: 'Yes, reservations can be easily booked online through our Reservations page with instant confirmation code and calendar reminders.',
    answerUr: 'جی ہاں، آپ ہماری ریزرویشنز پیج کے ذریعے باآسانی آن لائن ٹیبل بک کر سکتے ہیں، جس سے فوری تصدیقی کوڈ ملتا ہے۔',
  },
  {
    questionEn: 'What payment methods do you accept?',
    questionUr: 'ادائیگی کے کون سے طریقے قبول کیے جاتے ہیں؟',
    answerEn: 'We currently accept Cash on Delivery and Pay at Counter. Online payment via JazzCash, Easypaisa, and Debit/Credit cards is coming soon.',
    answerUr: 'ہم فی الوقت کیش آن ڈلیوری اور کاؤنٹر پر نقد ادائیگی قبول کرتے ہیں۔ جاز کیش، ایزی پیسہ اور کارڈ جلد فعال ہو رہے ہیں۔',
  },
];
